package com.android.cows.fahrgemeinschaft;

import android.content.Context;
import android.os.Bundle;
import android.util.Log;

import com.google.android.gms.gcm.GoogleCloudMessaging;

import java.io.IOException;
import java.util.UUID;

/**
 * Created by Lennart on 13.05.2016.
 */

public class MyGcmSend {

    private static final String TAG = "MyGcmSend";
    private String message;



    protected void send(String message, Context con) {



        // Add custom implementation, as needed.
        final GoogleCloudMessaging gcm = GoogleCloudMessaging.getInstance(con);
        final String senderId = con.getString(R.string.gcm_defaultSenderId);
        final String msgId = nextMessageId();

        Log.i(TAG, "Try Sending Message");

        String msg = "";
        try {
            Bundle payload = new Bundle();
//            payload.putString("task_category", "chat");
//            payload.putString("task_category", "group");
            payload.putString("task_category", "user");
            String id = msgId;
            gcm.send(senderId + "@gcm.googleapis.com", id, payload);
            msg = "Sent message completed";
        } catch (IOException ex) {
            msg = "Error :" + ex.getMessage();
        }
        Log.i(TAG, msg);
    }

    /**
     * Returns a random message id to uniquely identify a message.
     * <p>
     * <p>Note: This is generated by a pseudo random number generator for
     * illustration purpose, and is not guaranteed to be unique.
     */
    public String nextMessageId() {
        return "m-" + UUID.randomUUID().toString();
    }
}